(function () {
  'use strict';

  window.LibraryData = window.LibraryData || {};

window.LibraryData.MAP_IMAGE_ES = './assets/images/ESPANOL.png';
window.LibraryData.MAP_IMAGE_EN = './assets/images/INGLES.png';
window.LibraryData.ACTIVITIES_URL = './assets/data/activities.json?v=games-9';

window.LibraryData.STRINGS = {
  es: {
    'nav.back': 'Volver',
    'help.button': 'Ayuda',
    'help.title': '¿Necesitas ayuda?',
    'help.message': 'Ya avisamos al equipo de la biblioteca. Una persona se acercará para ayudarte; por favor espera aquí.',
    'help.dismiss': 'Cerrar',
    'help.location_unknown': 'No registrada',
    'menu.title': '¿Cómo puedo ayudarte?',
    'menu.navigation': '¿A dónde voy?',
    'menu.navigation.desc': 'Te guío paso a paso a tu destino',
    'menu.shelves': 'Buscar libro',
    'menu.shelves.desc': 'Busca por tema en las estanterías',
    'menu.books': 'Servicios de libros',
    'menu.books.desc': 'Préstamo y devolución',
    'menu.info': 'Información',
    'menu.info.desc': 'Horarios, noticias y preguntas frecuentes',
    'menu.events': 'Eventos',
    'menu.events.desc': 'Trivia y actividades',
    'menu.primary_service': 'Servicio principal',
    'menu.start': 'Comenzar',
    'menu.start_arrow': 'Comenzar ➔',

    'nav.you_are_here': 'Aquí estás',
    'nav.your_dest': 'Tu destino',
    'nav.screen_title': 'Selecciona un destino',
    'nav.cat.rooms': 'Salas de estudio',
    'nav.cat.services': 'Servicios',
    'nav.cat.access': 'Accesos',
    'nav.guide_me': 'Llevame',
    'nav.done': 'Listo',
    'nav.directions': 'Indicaciones',
    'nav.map_label': 'Mapa del piso',
    'nav.quick_hint': 'Elige un destino y te mostrare la ruta en el mapa',
    'dest.reception': 'Recepción',
    'dest.coordination': 'Coordinación',
    'dest.elevator': 'Ascensor',
    'dest.stairs_up': 'Escaleras subida',
    'dest.stairs_down': 'Escaleras bajada',
    'dest.stairs_emergency': 'Escaleras emergencia ',
    'dest.restroom_m': 'Baño hombres',
    'dest.restroom_f': 'Baño mujeres',
    'dest.restroom_accessible': 'Baño minusválidos',
    'dest.room_251': 'Sala 251',
    'dest.room_252c': 'Sala 252C',
    'dest.room_254': 'Sala 254',
    'dest.room_255': 'Sala 255',
    'dest.room_255a': 'Sala 255A',
    'dest.room_255b': 'Sala 255B',
    'dest.room_255c': 'Sala 255C',
    'dest.room_255d': 'Sala 255D',
    'dest.room_256': 'Sala 256',
    'dest.room_257': 'Sala 257',
    'dest.room_259a': 'Sala 259A',
    'dest.room_259g': 'Sala 259G',
    'dest.book_lift': 'Subidor de libros',
    'dest.material_maintenance_workshop': 'Taller mantenimiento material',
    'dest.sterilization_space': 'Espacio esterilización',
    'dest.map.restroom_accessible': 'Baño minusválidos',
    'dest.map.material_maintenance_workshop': 'Taller material',
    'dest.map.book_lift': 'Subidor de libros',
    'dest.col_engineering': 'Ingenieria',
    'dest.col_sciences': 'Ciencias',
    'dest.col_humanities': 'Humanidades',
    'dest.col_social': 'Ciencias sociales',
    'dest.col_arts': 'Artes',
    'dest.entry': 'Entrada',
    'dest.exit': 'Salida',
    'books.screen_title': 'Servicios de libros',
    'books.borrow': 'Préstamo',
    'books.borrow_desc': 'Quiero pedir un libro',
    'books.return': 'Devolución',
    'books.return_desc': 'Quiero devolver un libro',
    'books.borrow_title': 'Préstamo de libros',
    'books.borrow_message': 'Para solicitar un préstamo, por favor dirígete a Recepción donde un bibliotecario te asistirá, o utiliza la estación de autoservicio.',
    'books.return_title': 'Devolución de libros',
    'books.return_message': 'Para devolver un libro, por favor dirígete a Recepción o utiliza el buzón de devolución disponible en el primer piso.',
    'books.go_reception': 'Llévame a Recepción',
    'books.back_options': 'Volver a opciones',
    'books.hero_eyebrow': 'Servicios disponibles',
    'books.hero_title': 'Préstamo y devolución sin perderte',
    'books.hero_copy': 'Selecciona lo que quieres hacer y te mostraré los pasos más claros para continuar.',
    'books.tap_continue': 'Toca para continuar',
    'books.detail_eyebrow': 'Servicios de libros',
    'books.borrow_step_1_title': 'Encuentra el libro',
    'books.borrow_step_1_desc': 'En las estanterías',
    'books.borrow_step_2_title': 'Ve a Recepción',
    'books.borrow_step_2_desc': 'Con tu carné',
    'books.borrow_step_3_title': 'Llévalo contigo',
    'books.borrow_step_3_desc': 'Hasta 5 libros',
    'books.return_step_1_title': 'Trae el libro',
    'books.return_step_1_desc': 'Revisa que esté completo',
    'books.return_step_2_title': 'Ve a Recepción',
    'books.return_step_2_desc': 'O al buzón de devolución',
    'books.return_step_3_title': 'Confirma la entrega',
    'books.return_step_3_desc': 'Finaliza el proceso',
    'info.screen_title': 'Informacion',
    'info.hours': 'Horarios',
    'info.news': 'Noticias',
    'info.faq': 'Preguntas frecuentes',
    'info.today': 'Hoy',
    'info.news_title': 'Noticias Uniandes',
    'info.news_copy': 'Consulta las noticias mas recientes directamente desde el portal oficial de la Universidad.',
    'info.news_cta': 'Abrir noticias',
    'info.news_hint': 'Si el panel no carga, usa este acceso directo.',
    'info.hours_value': '7:00 AM - 9:00 PM',
    'info.day_mon': 'Lunes',
    'info.day_tue': 'Martes',
    'info.day_wed': 'Miercoles',
    'info.day_thu': 'Jueves',
    'info.day_fri': 'Viernes',
    'info.day_sat': 'Sabado',
    'info.day_sun': 'Domingo',
    'info.closed': 'Cerrado',
    'events.screen_title': 'Eventos',
    'events.question': 'Pregunta',
    'events.of': 'de',
    'events.score': 'Puntos:',
    'events.next': 'Siguiente',
    'events.result_title': 'Resultado final',
    'events.result_great': 'Excelente!',
    'events.result_good': 'Bien hecho!',
    'events.result_ok': 'Sigue intentando!',
    'events.result_copy_great': 'Conoces la biblioteca a fondo. ¿Listo para volver a probar?',
    'events.result_copy_ok': 'No te preocupes, la practica hace al maestro. ¿Otra vuelta?',
    'events.result_correct': 'Correctas',
    'events.result_incorrect': 'Incorrectas',
    'events.result_time': 'Tiempo',
    'events.play_again': 'Jugar otra vez',
    'events.try_again': 'Volver a intentar',
    'events.back_menu': 'Salir al menu',
    'events.select_activity': 'Elige una actividad',
    'events.available_now': 'Disponible ahora',
    'events.coming_soon': 'Proximamente',
    'events.badge_trivia': 'Trivia',
    'events.badge_game': 'Juego',
    'events.library_arcade': 'Zona de eventos',
    'events.library_copy': 'Actividades disponibles ahora mismo!',
    'events.wordsearch_progress': 'Palabras encontradas',
    'events.wordsearch_clear': 'Limpiar seleccion',
    'events.wordsearch_hint': 'Toca letras vecinas para formar cada palabra.',
    'events.wordsearch_done': 'Encontraste todas las palabras!',
    'events.memory_progress': 'Pares encontrados',
    'events.memory_attempts': 'Intentos',
    'events.memory_author': 'Autor',
    'events.memory_work': 'Obra',
    'events.memory_hint': 'Encuentra el autor y su obra correspondiente.',
    'events.memory_done': 'Completaste la memoria de autores!',
    'shelves.screen_title': 'Buscar libro por tema',
    'shelves.eyebrow': 'Estanterias · 6 secciones',
    'shelves.map_destination': 'Tu destino',
    'shelves.this_is': 'Esta es',
    'shelves.go_here': 'Acá vas',
    'shelves.panel_hint': 'Toca una estanteria para ver sus temas',
    'shelves.search_placeholder': 'Busca un tema...',
    'shelves.search_meta_default': 'Explora las estanterias o escribe un tema.',
    'shelves.search_results': 'resultados',
    'shelves.search_empty': 'No encontramos coincidencias. Intenta con otra palabra clave.',
    'shelves.select_hint': 'Selecciona una estanteria para ver su ubicacion',
    'shelves.shelf_label': 'Estanteria',
    'shelves.section_label': 'Seccion',
    'shelves.no_results': 'Sin resultados para tu busqueda',
    'shelves.topics_count': 'temas',
    'shelves.view_topics': 'Ver temas',
    'shelves.hide_topics': 'Ocultar temas',
    'shelves.tap_topic': 'Toca un tema para ver la ubicacion',
    'feedback.title': '¿Cómo fue tu experiencia?',
    'feedback.bad': 'Mala',
    'feedback.ok': 'Regular',
    'feedback.great': 'Buena',
    'feedback.excelente': 'Excelente',
    'feedback.bueno': 'Bueno',
    'feedback.regular': 'Regular',
    'feedback.malo': 'Malo',
    'feedback.pesimo': 'Pésimo',
    'feedback.thanks': '¡Gracias por tu opinión!',
    'feedback.caption': 'Tu opinión ayuda a que Nova atienda mejor',
    'feedback.comment_prompt': '¿Quieres agregar algún comentario? (opcional)',
    'feedback.comment_placeholder': 'Escribe aquí tu comentario...',
    'feedback.selected_rating': 'Elegiste',
    'feedback.send': 'Enviar'
  },
  en: {
    'nav.back': 'Back',
    'help.button': 'Help',
    'help.title': 'Need help?',
    'help.message': 'The library team has been notified. Someone will come over to help you; please wait here.',
    'help.dismiss': 'Close',
    'help.location_unknown': 'Not recorded',
    'menu.title': 'How can I help you?',
    'menu.navigation': 'Where do I go?',
    'menu.navigation.desc': "I'll guide you step by step to your destination",
    'menu.shelves': 'Search for books',
    'menu.shelves.desc': 'Search by subject on the shelves',
    'menu.books': 'Book services',
    'menu.books.desc': 'Borrow and return',
    'menu.info': 'Information',
    'menu.info.desc': 'Opening hours, news, and FAQs',
    'menu.events': 'Events',
    'menu.events.desc': 'Trivia and activities',
    'menu.primary_service': 'Main service',
    'menu.start': 'Start',
    'menu.start_arrow': 'Start ➔',
    'nav.you_are_here': 'You are here',
    'nav.your_dest': 'Your destination',
    'nav.screen_title': 'Select a destination',
    'nav.cat.rooms': 'Study rooms',
    'nav.cat.services': 'Services',
    'nav.cat.access': 'Access points',
    'nav.guide_me': 'Guide me',
    'nav.done': 'Done',
    'nav.directions': 'Directions',
    'nav.map_label': 'Floor map',
    'nav.quick_hint': 'Choose a destination and I will show the route on the map',
    'dest.reception': 'Reception',
    'dest.coordination': 'Coordination',
    'dest.elevator': 'Elevator',
    'dest.stairs_up': 'Stairs up',
    'dest.stairs_down': 'Stairs down',
    'dest.stairs_emergency': 'Emergency stairs',
    'dest.restroom_m': "Men's restroom",
    'dest.restroom_f': "Women's restroom",
    'dest.restroom_accessible': 'Accessible restroom',
    'dest.room_251': 'Room 251',
    'dest.room_252c': 'Room 252C',
    'dest.room_254': 'Room 254',
    'dest.room_255': 'Room 255',
    'dest.room_255a': 'Room 255A',
    'dest.room_255b': 'Room 255B',
    'dest.room_255c': 'Room 255C',
    'dest.room_255d': 'Room 255D',
    'dest.room_256': 'Room 256',
    'dest.room_257': 'Room 257',
    'dest.room_259a': 'Room 259A',
    'dest.room_259g': 'Room 259G',
    'dest.book_lift': 'Book lift',
    'dest.material_maintenance_workshop': 'Material maintenance workshop',
    'dest.sterilization_space': 'Sterilization space',
    'dest.map.restroom_accessible': 'Accessible restroom',
    'dest.map.material_maintenance_workshop': 'Material workshop',
    'dest.map.book_lift': 'Book lift',
    'dest.col_engineering': 'Engineering',
    'dest.col_sciences': 'Sciences',
    'dest.col_humanities': 'Humanities',
    'dest.col_social': 'Social sciences',
    'dest.col_arts': 'Arts',
    'dest.entry': 'Entrance',
    'dest.exit': 'Exit',
    'books.screen_title': 'Book services',
    'books.borrow': 'Borrow',
    'books.borrow_desc': 'I want to borrow a book',
    'books.return': 'Return',
    'books.return_desc': 'I want to return a book',
    'books.borrow_title': 'Book borrowing',
    'books.borrow_message': 'To borrow a book, please go to Reception where a librarian will assist you, or use the self-checkout station.',
    'books.return_title': 'Book return',
    'books.return_message': 'To return a book, please go to Reception or use the return drop-box available on the first floor.',
    'books.go_reception': 'Take me to Reception',
    'books.back_options': 'Back to options',
    'books.hero_eyebrow': 'Available services',
    'books.hero_title': 'Borrowing and returns without the guesswork',
    'books.hero_copy': 'Choose what you need and I will show the clearest next step inside the library.',
    'books.tap_continue': 'Tap to continue',
    'books.detail_eyebrow': 'Book services',
    'books.borrow_step_1_title': 'Find the book',
    'books.borrow_step_1_desc': 'On the shelves',
    'books.borrow_step_2_title': 'Go to Reception',
    'books.borrow_step_2_desc': 'With your ID card',
    'books.borrow_step_3_title': 'Take it with you',
    'books.borrow_step_3_desc': 'Up to 5 books',
    'books.return_step_1_title': 'Bring the book',
    'books.return_step_1_desc': 'Check that it is complete',
    'books.return_step_2_title': 'Go to Reception',
    'books.return_step_2_desc': 'Or use the return drop-box',
    'books.return_step_3_title': 'Confirm the return',
    'books.return_step_3_desc': 'Finish the process',
    'info.screen_title': 'Information',
    'info.hours': 'Hours',
    'info.news': 'News',
    'info.faq': 'Frequently asked questions',
    'info.today': 'Today',
    'info.news_title': 'Uniandes news',
    'info.news_copy': 'Check the latest stories directly from the official Universidad de los Andes news portal.',
    'info.news_cta': 'Open news',
    'info.news_hint': 'If the panel does not load, use this direct access.',
    'info.hours_value': '7:00 AM - 9:00 PM',
    'info.day_mon': 'Monday',
    'info.day_tue': 'Tuesday',
    'info.day_wed': 'Wednesday',
    'info.day_thu': 'Thursday',
    'info.day_fri': 'Friday',
    'info.day_sat': 'Saturday',
    'info.day_sun': 'Sunday',
    'info.closed': 'Closed',
    'events.screen_title': 'Events',
    'events.question': 'Question',
    'events.of': 'of',
    'events.score': 'Score:',
    'events.next': 'Next',
    'events.result_title': 'Final result',
    'events.result_great': 'Excellent!',
    'events.result_good': 'Well done!',
    'events.result_ok': 'Keep trying!',
    'events.result_copy_great': 'You know the library well. Ready to try again?',
    'events.result_copy_ok': 'Do not worry, practice makes perfect. Another round?',
    'events.result_correct': 'Correct',
    'events.result_incorrect': 'Incorrect',
    'events.result_time': 'Time',
    'events.play_again': 'Play again',
    'events.try_again': 'Try again',
    'events.back_menu': 'Exit to menu',
    'events.select_activity': 'Choose an activity',
    'events.available_now': 'Available now',
    'events.coming_soon': 'Coming soon',
    'events.badge_trivia': 'Trivia',
    'events.badge_game': 'Game',
    'events.library_arcade': 'Events arcade',
    'events.library_copy': 'Activities available right now!',
    'events.wordsearch_progress': 'Words found',
    'events.wordsearch_clear': 'Clear selection',
    'events.wordsearch_hint': 'Tap neighboring letters to form each word.',
    'events.wordsearch_done': 'You found every word!',
    'events.memory_progress': 'Pairs found',
    'events.memory_attempts': 'Attempts',
    'events.memory_author': 'Author',
    'events.memory_work': 'Work',
    'events.memory_hint': 'Find each author and the matching work.',
    'events.memory_done': 'You completed the author memory game!',
    'shelves.screen_title': 'Find book by topic',
    'shelves.eyebrow': 'Shelves · 6 sections',
    'shelves.map_destination': 'Your destination',
    'shelves.this_is': 'This shelf',
    'shelves.go_here': 'You go here',
    'shelves.panel_hint': 'Tap a shelf to see its topics',
    'shelves.search_placeholder': 'Search a topic...',
    'shelves.search_meta_default': 'Browse the shelves or type a topic.',
    'shelves.search_results': 'results',
    'shelves.search_empty': 'No matches found. Try another keyword.',
    'shelves.select_hint': 'Select a shelf to see its location',
    'shelves.shelf_label': 'Shelf',
    'shelves.section_label': 'Section',
    'shelves.no_results': 'No results for your search',
    'shelves.topics_count': 'topics',
    'shelves.view_topics': 'View topics',
    'shelves.hide_topics': 'Hide topics',
    'shelves.tap_topic': 'Tap a topic to see its location',
    'feedback.title': 'How was your experience?',
    'feedback.bad': 'Bad',
    'feedback.ok': 'Okay',
    'feedback.great': 'Great',
    'feedback.excelente': 'Excellent',
    'feedback.bueno': 'Good',
    'feedback.regular': 'Okay',
    'feedback.malo': 'Bad',
    'feedback.pesimo': 'Very bad',
    'feedback.thanks': 'Thank you for your feedback!',
    'feedback.caption': 'Your feedback helps Nova assist better',
    'feedback.comment_prompt': 'Would you like to add a comment? (optional)',
    'feedback.comment_placeholder': 'Write your comment here...',
    'feedback.selected_rating': 'You chose',
    'feedback.send': 'Send'
  }
};

window.LibraryData.SCREEN_TITLES = {
  menu: 'menu.title',
  navigation: 'nav.screen_title',
  'navigation-guide': 'nav.directions',
  shelves: 'shelves.screen_title',
  books: 'books.screen_title',
  info: 'info.screen_title',
  events: 'events.screen_title',
  feedback: 'feedback.title'
};

window.LibraryData.TOPBAR_SCREENS = ['menu', 'navigation', 'navigation-guide', 'shelves', 'books', 'info', 'events', 'feedback'];

window.LibraryData.MENU_CATEGORIES = {
  navigation: '¿A donde voy?',
  shelves: 'Buscar libro',
  books: 'Servicios de libro',
  info: 'Informacion',
  events: 'Eventos'
};

window.LibraryData.NAV_DEST_CATEGORIES = {
  room_251: 'rooms',
  room_252c: 'rooms',
  room_254: 'rooms',
  room_255: 'rooms',
  room_255a: 'rooms',
  room_255b: 'rooms',
  room_255c: 'rooms',
  room_255d: 'rooms',
  room_256: 'rooms',
  room_257: 'rooms',
  room_259a: 'rooms',
  room_259g: 'rooms',
  reception: 'services',
  coordination: 'services',
  restroom_m: 'services',
  restroom_f: 'services',
  restroom_accessible: 'services',
  material_maintenance_workshop: 'services',
  sterilization_space: 'services',
  book_lift: 'services',
  entry: 'access',
  exit: 'access',
  elevator: 'access',
  stairs_up: 'access',
  stairs_down: 'access',
  stairs_emergency: 'access'
};

window.LibraryData.DEST_CATEGORY_LABELS = {
  rooms: 'Salas de estudio',
  services: 'Servicios',
  access: 'Accesos'
};

window.LibraryData.NAV_CATEGORIES = [
  {
    id: 'rooms',
    titleKey: 'nav.cat.rooms',
    items: [
      { id: 'room_251', nameKey: 'dest.room_251' },
      { id: 'room_252c', nameKey: 'dest.room_252c' },
      { id: 'room_254', nameKey: 'dest.room_254' },
      { id: 'room_255', nameKey: 'dest.room_255' },
      { id: 'room_255a', nameKey: 'dest.room_255a' },
      { id: 'room_255b', nameKey: 'dest.room_255b' },
      { id: 'room_255c', nameKey: 'dest.room_255c' },
      { id: 'room_255d', nameKey: 'dest.room_255d' },
      { id: 'room_256', nameKey: 'dest.room_256' },
      { id: 'room_257', nameKey: 'dest.room_257' },
      { id: 'room_259a', nameKey: 'dest.room_259a' },
      { id: 'room_259g', nameKey: 'dest.room_259g' }
    ]
  },
  {
    id: 'services',
    titleKey: 'nav.cat.services',
    items: [
      { id: 'reception', nameKey: 'dest.reception' },
      { id: 'coordination', nameKey: 'dest.coordination' },
      { id: 'restroom_m', nameKey: 'dest.restroom_m' },
      { id: 'restroom_f', nameKey: 'dest.restroom_f' },
      { id: 'restroom_accessible', nameKey: 'dest.restroom_accessible' },
      { id: 'material_maintenance_workshop', nameKey: 'dest.material_maintenance_workshop' },
      { id: 'sterilization_space', nameKey: 'dest.sterilization_space' },
      { id: 'book_lift', nameKey: 'dest.book_lift' }
    ]
  },
  {
    id: 'access',
    titleKey: 'nav.cat.access',
    items: [
      { id: 'entry', nameKey: 'dest.entry' },
      { id: 'exit', nameKey: 'dest.exit' },
      { id: 'elevator', nameKey: 'dest.elevator' },
      { id: 'stairs_up', nameKey: 'dest.stairs_up' },
      { id: 'stairs_down', nameKey: 'dest.stairs_down' },
      { id: 'stairs_emergency', nameKey: 'dest.stairs_emergency' }
    ]
  }
];

window.LibraryData.MAP_COORDS = {
  you_are_here: { x: 44.5, y: 43 },
  reception: { x: 43.76, y: 22 },
  coordination: { x: 94.6, y: 10 },
  elevator: { x: 59.4, y: 22 },
  stairs_up: [
    { x: 41.7, y: 44 },
    { x: 60.3, y: 44 }
  ],
  stairs_down: [
    { x: 41.7, y: 80.5 },
    { x: 60.3, y: 80.5 }
  ],
  stairs_emergency: [
    { x: 29.9, y: 32.5 },
    { x: 70, y: 32.5 }
  ],
  entry: { x: 51.2, y: 21 },
  exit: { x: 62.92, y: 22 },
  book_lift: { x: 39.65, y: 19 },
  material_maintenance_workshop: { x: 3.5, y: 37 },
  sterilization_space: { x: 6.5, y: 76.2 },
  restroom_m: { x: 76.53, y: 32.5 },
  restroom_f: { x: 21.72, y: 32.5 },
  restroom_accessible: { x: 17.76, y: 32.5 },
  room_251: { x: 22.14, y: 45.8 },
  room_252c: { x: 6.5, y: 90 },
  room_254: { x: 96.3, y: 40.1 },
  room_255: { x: 96.3, y: 32.6 },
  room_255a: { x: 56.38, y: 71 },
  room_255b: { x: 52.72, y: 71 },
  room_255c: { x: 49.11, y: 71 },
  room_255d: { x: 45.51, y: 71 },
  room_256: { x: 96.3, y: 25.1 },
  room_257: { x: 96.3, y: 17.6 },
  room_259a: { x: 79.65, y: 32.5 },
  room_259g: { x: 79.22, y: 45.8 },
  shelf_01_single: { x: 93.3, y: 69.5 },
  shelf_02_small: { x: 90.7, y: 49.5 },
  shelf_02_large: { x: 90.7, y: 69.5 },
  shelf_03_small: { x: 88.1, y: 49.5 },
  shelf_03_large: { x: 88.1, y: 69.5 },
  shelf_04_small: { x: 85.5, y: 49.5 },
  shelf_04_large: { x: 85.5, y: 69.5 },
  shelf_05_small: { x: 83.1, y: 49.5 },
  shelf_05_large: { x: 83.1, y: 69.5},
  shelf_06_single: { x: 81.3, y: 49.5 },
  shelf_07_single: { x: 77.2, y: 49.5 },
  shelf_08_small: { x: 74.8, y: 49.5 },
  shelf_08_large: { x: 74.8, y: 69.5 },
  shelf_09_small: { x: 72.2, y: 49.5 },
  shelf_09_large: { x: 72.2, y: 69.5 },
  shelf_10_small: { x: 69.7, y: 49.5 },
  shelf_10_large: { x: 69.7, y: 69.5 },
  shelf_11_small: { x: 67.1, y: 49.5 },
  shelf_11_large: { x: 67.1, y: 69.5 },
  shelf_12_small: { x: 64.6, y: 49.5 },
  shelf_12_large: { x: 64.6, y: 69.5 },
  shelf_13_small: { x: 36.4, y: 49.5 },
  shelf_13_large: { x: 36.4, y: 69.5 },
  shelf_14_small: { x: 33.6, y: 49.5 },
  shelf_14_large: { x: 33.6, y: 69.5 },
  shelf_15_small: { x: 31, y: 49.5 },
  shelf_15_large: { x: 31, y: 69.5 },
  shelf_16_small: { x: 28.7, y: 49.5 },
  shelf_16_large: { x: 28.7, y: 69.5 },
  shelf_17_small: { x: 26.1, y: 49.5 },
  shelf_17_large: { x: 26.1, y: 69.5 },
  shelf_18_single: { x: 23.8, y: 49.5 },
  shelf_19_small: { x: 19.7, y: 69.5 },
  shelf_20_small: { x: 17.3, y: 69.5 },
  shelf_21_small: { x: 14.7, y: 69.5 },
  shelf_22_small: { x: 12.2, y: 69.5 }
};

window.LibraryData.HOURS = {
  schedule: [
    { dayKey: 'info.day_mon', time: '7:00 AM - 9:00 PM' },
    { dayKey: 'info.day_tue', time: '7:00 AM - 9:00 PM' },
    { dayKey: 'info.day_wed', time: '7:00 AM - 9:00 PM' },
    { dayKey: 'info.day_thu', time: '7:00 AM - 9:00 PM' },
    { dayKey: 'info.day_fri', time: '7:00 AM - 9:00 PM' },
    { dayKey: 'info.day_sat', time: '8:00 AM - 4:00 PM' },
    { dayKey: 'info.day_sun', closedKey: 'info.closed' }
  ]
};

window.LibraryData.FAQS = [
  {
    q: { es: 'Como puedo prestar un libro?', en: 'How can I borrow a book?' },
    a: { es: 'Dirigete a Recepcion con tu carnet universitario. El personal te asistira con el proceso de prestamo. Tambien puedes usar la estacion de autoservicio.', en: 'Go to Reception with your university ID. Staff will assist you with the borrowing process. You can also use the self-checkout station.' }
  },
  {
    q: { es: 'Cuantos libros puedo tener prestados?', en: 'How many books can I have on loan?' },
    a: { es: 'Los estudiantes de pregrado pueden tener hasta 5 libros prestados simultaneamente. Estudiantes de posgrado pueden tener hasta 8.', en: 'Undergraduate students can have up to 5 books on loan simultaneously. Graduate students can have up to 8.' }
  },
  {
    q: { es: 'Donde estan los banos?', en: 'Where are the restrooms?' },
    a: { es: 'Los banos estan ubicados en el costado derecho de la biblioteca. Puedes usar la opcion "Adonde voy?" para que te guie.', en: 'The restrooms are located on the right side of the library. You can use the "Where do I go?" option for directions.' }
  },
  {
    q: { es: 'Puedo reservar una sala de estudio?', en: 'Can I reserve a study room?' },
    a: { es: 'Si, las salas de estudio se pueden reservar a traves del sistema IRUS o directamente en Recepcion.', en: 'Yes, study rooms can be reserved through the IRUS system or directly at Reception.' }
  },
  {
    q: { es: 'Hay impresoras disponibles?', en: 'Are printers available?' },
    a: { es: 'Si, hay impresoras disponibles para los estudiantes. Consulta en Recepcion sobre el servicio de impresion.', en: 'Yes, printers are available for students. Ask at Reception about the printing service.' }
  },
  {
    q: { es: 'Que hago si pierdo un libro prestado?', en: 'What if I lose a borrowed book?' },
    a: { es: 'Dirigete a Recepcion lo antes posible para reportar la perdida. El personal te indicara el procedimiento a seguir.', en: 'Go to Reception as soon as possible to report the loss. Staff will guide you through the procedure.' }
  }
];

window.LibraryData.TAB_SERVICE_MAP = {
  hours: 'Informacion',
  news: 'Noticias',
  faq: 'Preguntas frecuentes'
};

window.LibraryData.RATING_MAP = {
  excelente: 'Excelente',
  bueno: 'Bueno',
  regular: 'Regular',
  malo: 'Malo',
  pesimo: 'Pésimo'
};

window.LibraryData.SHELF_NUMBERS = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22'];

window.LibraryData.SHELF_TOPIC_TRANSLATIONS = {
  'SIMULACIÓN': 'Simulation',
  'ARQUITECTURA DE SOFTWARE': 'Software architecture',
  'REDES Y CONECTIVIDAD': 'Computer networks',
  'INTELIGENCIA ARTIFICIAL': 'Artificial intelligence',
  'SISTEMAS OPERATIVOS': 'Operating systems',
  'BASES DE DATOS': 'Database systems',
  'SEGURIDAD INFORMÁTICA': 'Information security',
  'DISEÑO MULTIMEDIA': 'Multimedia design',
  'LENGUAJES DE PROGRAMACIÓN': 'Programming languages',
  'METODOLOGÍA CIENTÍFICA': 'Research methods',
  'FILOSOFÍA DE LA CIENCIA': 'Philosophy of science',
  'MATEMÁTICAS - ENSEÑANZA': 'Mathematics education',
  'MATEMÁTICAS - FUNDAMENTOS': 'Foundations of mathematics',
  'MATEMÁTICAS - HISTORIA': 'History of mathematics',
  'LÓGICA MATEMÁTICA': 'Mathematical logic',
  'CIENCIA Y TECNOLOGÍA - HISTORIA': 'History of science and technology',
  'MATEMÁTICAS': 'Mathematics',
  'ÁLGEBRA': 'Algebra',
  'ÁLGEBRA LINEAL': 'Linear algebra',
  'TOPOLOGÍA': 'Topology',
  'CÁLCULO': 'Calculus',
  'PRE-CÁLCULO': 'Pre-calculus',
  'TEORÍA DE LOS NÚMEROS': 'Number theory',
  'ECUACIONES DIFERENCIALES': 'Differential equations',
  'GEOMETRÍA': 'Geometry',
  'PROBABILIDAD': 'Probability',
  'TEORÍA DEL JUEGO': 'Game theory',
  'CÁLCULO VECTORIAL': 'Vector calculus',
  'ANÁLISIS DE GEOMETRÍA': 'Geometric analysis',
  'ANÁLISIS NUMÉRICO': 'Numerical analysis',
  'ESTADÍSTICA': 'Statistics',
  'ANÁLISIS MULTIVARIABLE': 'Multivariate analysis',
  'OPTIMIZACIÓN': 'Optimization',
  'ASTRONOMÍA': 'Astronomy',
  'FÍSICA': 'Physics',
  'FÍSICA - BIOGRAFÍAS': 'Physicists - biography',
  'RELATIVIDAD': 'Relativity',
  'TEORÍA CUÁNTICA': 'Quantum theory',
  'COSMOLOGÍA': 'Cosmology',
  'TOPOGRAFÍA': 'Surveying',
  'FÍSICA - FUNDAMENTOS': 'Fundamentals of physics',
  'ELECTROMAGNETISMO': 'Electromagnetism',
  'MECÁNICA ESTADÍSTICA': 'Statistical mechanics',
  'FÍSICA TERMODINÁMICA': 'Thermal physics',
  'ELECTRODINÁMICA': 'Electrodynamics',
  'FÍSICA NUCLEAR': 'Nuclear physics',
  'MECÁNICA DE FLUIDOS': 'Fluid mechanics',
  'ÓPTICA': 'Optics',
  'MODELOS NUCLEARES': 'Nuclear models',
  'QUÍMICA GENERAL': 'General chemistry',
  'ANÁLISIS QUÍMICO': 'Chemical analysis',
  'QUÍMICA INORGÁNICA': 'Inorganic chemistry',
  'QUÍMICA ORGÁNICA': 'Organic chemistry',
  'FISICOQUÍMICA': 'Physical chemistry',
  'QUÍMICA TERMODINÁMICA': 'Chemical thermodynamics',
  'MACROMOLÉCULAS': 'Macromolecules',
  'MINERALES': 'Mineralogy',
  'GEOLOGÍA': 'Geology',
  'ANTROPOLOGÍA BIOLÓGICA': 'Biological anthropology',
  'BIOLOGÍA': 'Biology',
  'BIOESTADÍSTICA': 'Biostatistics',
  'METEOROLOGÍA': 'Meteorology',
  'GEOQUÍMICA': 'Geochemistry',
  'BIOQUÍMICA': 'Biochemistry',
  'ECOLOGÍA': 'Ecology',
  'MICROBIOLOGÍA': 'Microbiology',
  'BOTÁNICA': 'Botany',
  'FITOPATOLOGÍA': 'Plant pathology',
  'BIOLOGÍA MOLECULAR': 'Molecular biology',
  'GENÉTICA': 'Genetics',
  'MICOLOGÍA': 'Mycology',
  'ZOOLOGÍA': 'Zoology',
  'INVERTEBRADOS': 'Invertebrates',
  'DIBUJO EN INGENIERÍA': 'Engineering drawing',
  'HISTORIA DE LA TECNOLOGÍA': 'History of technology',
  'INGENIERÍA BIOMÉDICA': 'Biomedical engineering',
  'MEDICINA SOCIAL': 'Social medicine',
  'ANATOMÍA': 'Anatomy',
  'HISTOLOGÍA': 'Histology',
  'INSECTOS': 'Insects',
  'MAMÍFEROS': 'Mammals',
  'AVES': 'Birds',
  'FISIOLOGÍA MÉDICA': 'Human physiology',
  'NEUROCIENCIA': 'Neuroscience',
  'MEDICINA FORENSE': 'Forensic medicine',
  'PATOLOGÍA': 'Pathology',
  'INMUNOLOGÍA': 'Immunology',
  'HEMATOLOGÍA': 'Hematology',
  'NEUROLOGÍA': 'Neurology',
  'PSICOLOGÍA CLÍNICA': 'Clinical psychology',
  'FARMACOLOGÍA': 'Pharmacology',
  'SALUD PÚBLICA': 'Public health',
  'MICROBIOLOGÍA MÉDICA': 'Medical microbiology',
  'PSIQUIATRÍA': 'Psychiatry',
  'ENFERMEDADES INFECCIOSAS': 'Infectious diseases',
  'PEDIATRÍA': 'Pediatrics',
  'MATERIALES': 'Materials',
  'MECÁNICA APLICADA': 'Applied mechanics',
  'MECÁNICA DE MATERIALES': 'Strength of materials',
  'COMPOSICIÓN DE MATERIALES': 'Materials science',
  'INGENIERÍA': 'Engineering',
  'DISEÑO DE INGENIERÍA': 'Engineering design',
  'INGENIERÍA MECÁNICA': 'Mechanical engineering',
  'INGENIERÍA DE POLÍMEROS': 'Polymer engineering',
  'NANOTECNOLOGÍA': 'Nanotechnology',
  'INGENIERÍA ELÉCTRICA': 'Electrical engineering',
  'TELECOMUNICACIONES': 'Telecommunications',
  'MICROELECTRÓNICA': 'Microelectronics',
  'ELECTRÓNICA': 'Electronics',
  'COMUNICACIÓN DIGITAL': 'Digital communications',
  'CIRCUITOS ELÉCTRICOS': 'Electrical circuits',
  'PROCESAMIENTO DE SEÑALES': 'Signal processing',
  'DISEÑO DIGITAL': 'Digital design',
  'TERMODINÁMICA': 'Thermodynamics',
  'INGENIERÍA CIVIL': 'Civil engineering',
  'MECÁNICA DE SUELOS': 'Soil mechanics',
  'INGENIERÍA DE CARRETERAS': 'Transportation engineering',
  'DISEÑO DE ESTRUCTURAS': 'Structural design',
  'INGENIERÍA DE PETRÓLEOS': 'Petroleum engineering',
  'INGENIERÍA HIDRÁULICA': 'Hydraulics',
  'INGENIERÍA AMBIENTAL': 'Environmental engineering',
  'INGENIERÍA DEL AGUA': 'Water resources engineering',
  'GESTIÓN DE RESIDUOS': 'Waste management',
  'INGENIERÍA AUTOMOTRIZ': 'Automotive engineering',
  'SISTEMAS DE CONTROL Y ROBÓTICA': 'Control systems and robotics',
  'AGRICULTURA': 'Agriculture',
  'ZOOTECNIA': 'Animal husbandry',
  'GASTRONOMÍA': 'Culinary arts',
  'CONTABILIDAD': 'Accounting',
  'ADMINISTRACIÓN': 'Business administration',
  'TOMA DE DECISIONES': 'Decision making',
  'GERENCIA DE PROYECTOS': 'Project management',
  'ADMINISTRACIÓN DE OPERACIONES': 'Operations management',
  'MERCADEO': 'Marketing',
  'INGENIERÍA QUÍMICA': 'Chemical engineering',
  'PROCESOS QUÍMICOS': 'Chemical process engineering',
  'QUÍMICA INDUSTRIAL': 'Industrial chemistry',
  'TECNOLOGÍA DE ALIMENTOS': 'Food technology',
  'PETRÓLEO': 'Petroleum',
  'PLÁSTICOS': 'Plastics',
  'POLÍMEROS': 'Polymers',
  'METALURGÍA': 'Metallurgy',
  'MANUFACTURA': 'Manufacturing',
  'CONSTRUCCIÓN Y ACABADOS': 'Building construction',
  'LIBROS DE GRAN FORMATO': 'Large-format books'
};

window.LibraryData.SHELF_SIZE_LAYOUT = {
  '01': ['single', 'single'],
  '02': ['small', 'small', 'large', 'large'],
  '03': ['small', 'small', 'large', 'large'],
  '04': ['small', 'small', 'large', 'large'],
  '05': ['small', 'small', 'large', 'large'],
  '06': ['single'],
  '07': ['single'],
  '08': ['small', 'small', 'large', 'large'],
  '09': ['small', 'small', 'large', 'large'],
  '10': ['small', 'small', 'large', 'large'],
  '11': ['small', 'small', 'large', 'large'],
  '12': ['small', 'small', 'large', 'large'],
  '13': ['small', 'small', 'large', 'large'],
  '14': ['small', 'small', 'large', 'large'],
  '15': ['small', 'small', 'large', 'large'],
  '16': ['small', 'small', 'large', 'large'],
  '17': ['small', 'small', 'large', 'large'],
  '18': ['single'],
  '19': ['small', 'small'],
  '20': ['small', 'small'],
  '21': ['small', 'small'],
  '22': ['small', 'small']
};

window.LibraryData.SHELF_TOPICS = [
  { topics: ['SIMULACIÓN', 'ARQUITECTURA DE SOFTWARE'], shelf: '01' },
  { topics: ['REDES Y CONECTIVIDAD', 'INTELIGENCIA ARTIFICIAL'], shelf: '01' },
  { topics: ['SISTEMAS OPERATIVOS', 'BASES DE DATOS'], shelf: '02' },
  { topics: ['SEGURIDAD INFORMÁTICA', 'INTELIGENCIA ARTIFICIAL', 'DISEÑO MULTIMEDIA'], shelf: '02' },
  { topics: ['LENGUAJES DE PROGRAMACIÓN', 'SISTEMAS OPERATIVOS'], shelf: '02' },
  { topics: ['METODOLOGÍA CIENTÍFICA', 'FILOSOFÍA DE LA CIENCIA'], shelf: '02' },
  { topics: ['MATEMÁTICAS - ENSEÑANZA', 'MATEMÁTICAS - FUNDAMENTOS'], shelf: '03' },
  { topics: ['MATEMÁTICAS - HISTORIA', 'LÓGICA MATEMÁTICA'], shelf: '03' },
  { topics: ['CIENCIA Y TECNOLOGÍA - HISTORIA', 'MATEMÁTICAS'], shelf: '03' },
  { topics: ['ÁLGEBRA', 'ÁLGEBRA LINEAL'], shelf: '03' },
  { topics: ['TOPOLOGÍA', 'CÁLCULO'], shelf: '04' },
  { topics: ['CÁLCULO', 'PRE-CÁLCULO'], shelf: '04' },
  { topics: ['ÁLGEBRA LINEAL', 'TEORÍA DE LOS NÚMEROS', 'TOPOLOGÍA'], shelf: '04' },
  { topics: ['CÁLCULO', 'ECUACIONES DIFERENCIALES'], shelf: '04' },
  { topics: ['GEOMETRÍA', 'PROBABILIDAD'], shelf: '05' },
  { topics: ['PROBABILIDAD', 'TEORÍA DEL JUEGO'], shelf: '05' },
  { topics: ['CÁLCULO VECTORIAL', 'ANÁLISIS DE GEOMETRÍA'], shelf: '05' },
  { topics: ['TEORÍA DEL JUEGO', 'ANÁLISIS NUMÉRICO', 'PROBABILIDAD'], shelf: '05' },
  { topics: ['ESTADÍSTICA', 'ANÁLISIS MULTIVARIABLE'], shelf: '06' },
  { topics: ['OPTIMIZACIÓN', 'ASTRONOMÍA'], shelf: '07' },
  { topics: ['FÍSICA'], shelf: '08' },
  { topics: ['FÍSICA - BIOGRAFÍAS', 'RELATIVIDAD', 'TEORÍA CUÁNTICA'], shelf: '08' },
  { topics: ['COSMOLOGÍA', 'TOPOGRAFÍA', 'FÍSICA - FUNDAMENTOS'], shelf: '08' },
  { topics: ['TEORÍA CUÁNTICA', 'ELECTROMAGNETISMO'], shelf: '08' },
  { topics: ['MECÁNICA ESTADÍSTICA', 'FÍSICA TERMODINÁMICA', 'ELECTROMAGNETISMO'], shelf: '09' },
  { topics: ['ELECTRODINÁMICA', 'FÍSICA NUCLEAR'], shelf: '09' },
  { topics: ['MECÁNICA DE FLUIDOS', 'ÓPTICA'], shelf: '09' },
  { topics: ['MODELOS NUCLEARES', 'QUÍMICA GENERAL'], shelf: '09' },
  { topics: ['ANÁLISIS QUÍMICO', 'QUÍMICA INORGÁNICA'], shelf: '10' },
  { topics: ['QUÍMICA ORGÁNICA'], shelf: '10' },
  { topics: ['FISICOQUÍMICA', 'QUÍMICA TERMODINÁMICA'], shelf: '10' },
  { topics: ['MACROMOLÉCULAS', 'MINERALES', 'GEOLOGÍA'], shelf: '10' },
  { topics: ['ANTROPOLOGÍA BIOLÓGICA', 'BIOLOGÍA'], shelf: '11' },
  { topics: ['BIOESTADÍSTICA'], shelf: '11' },
  { topics: ['METEOROLOGÍA', 'GEOQUÍMICA'], shelf: '11' },
  { topics: ['BIOQUÍMICA', 'ECOLOGÍA'], shelf: '11' },
  { topics: ['MICROBIOLOGÍA', 'BOTÁNICA'], shelf: '12' },
  { topics: ['FITOPATOLOGÍA'], shelf: '12' },
  { topics: ['BIOLOGÍA MOLECULAR', 'GENÉTICA', 'MICROBIOLOGÍA'], shelf: '12' },
  { topics: ['MICOLOGÍA', 'ZOOLOGÍA', 'INVERTEBRADOS'], shelf: '12' },
  { topics: ['DIBUJO EN INGENIERÍA', 'HISTORIA DE LA TECNOLOGÍA', 'INGENIERÍA BIOMÉDICA'], shelf: '13' },
  { topics: ['MEDICINA SOCIAL', 'ANATOMÍA', 'HISTOLOGÍA'], shelf: '13' },
  { topics: ['INSECTOS', 'MAMÍFEROS', 'AVES'], shelf: '13' },
  { topics: ['FISIOLOGÍA MÉDICA', 'NEUROCIENCIA', 'MEDICINA FORENSE'], shelf: '13' },
  { topics: ['PATOLOGÍA', 'INMUNOLOGÍA', 'HEMATOLOGÍA'], shelf: '14' },
  { topics: ['NEUROLOGÍA', 'PSICOLOGÍA CLÍNICA'], shelf: '14' },
  { topics: ['FARMACOLOGÍA', 'SALUD PÚBLICA', 'MICROBIOLOGÍA MÉDICA'], shelf: '14' },
  { topics: ['PSIQUIATRÍA', 'ENFERMEDADES INFECCIOSAS', 'PEDIATRÍA'], shelf: '14' },
  { topics: ['MATERIALES', 'MECÁNICA APLICADA'], shelf: '15' },
  { topics: ['MECÁNICA DE MATERIALES', 'COMPOSICIÓN DE MATERIALES'], shelf: '15' },
  { topics: ['INGENIERÍA', 'DISEÑO DE INGENIERÍA', 'INGENIERÍA MECÁNICA'], shelf: '15' },
  { topics: ['INGENIERÍA DE POLÍMEROS', 'NANOTECNOLOGÍA', 'INGENIERÍA ELÉCTRICA'], shelf: '15' },
  { topics: ['TELECOMUNICACIONES', 'MICROELECTRÓNICA'], shelf: '16' },
  { topics: ['ELECTRÓNICA', 'COMUNICACIÓN DIGITAL'], shelf: '16' },
  { topics: ['CIRCUITOS ELÉCTRICOS', 'PROCESAMIENTO DE SEÑALES'], shelf: '16' },
  { topics: ['DISEÑO DIGITAL', 'TERMODINÁMICA'], shelf: '16' },
  { topics: ['INGENIERÍA CIVIL', 'MECÁNICA DE SUELOS'], shelf: '17' },
  { topics: ['INGENIERÍA DE CARRETERAS', 'DISEÑO DE ESTRUCTURAS'], shelf: '17' },
  { topics: ['INGENIERÍA MECÁNICA', 'INGENIERÍA DE PETRÓLEOS', 'INGENIERÍA HIDRÁULICA'], shelf: '17' },
  { topics: ['INGENIERÍA HIDRÁULICA', 'INGENIERÍA AMBIENTAL'], shelf: '17' },
  { topics: ['INGENIERÍA DEL AGUA', 'GESTIÓN DE RESIDUOS'], shelf: '18' },
  { topics: ['INGENIERÍA AMBIENTAL', 'INGENIERÍA AUTOMOTRIZ', 'SISTEMAS DE CONTROL Y ROBÓTICA'], shelf: '19' },
  { topics: ['AGRICULTURA', 'ZOOTECNIA', 'GASTRONOMÍA'], shelf: '19' },
  { topics: ['GASTRONOMÍA', 'CONTABILIDAD', 'ADMINISTRACIÓN'], shelf: '20' },
  { topics: ['TOMA DE DECISIONES', 'GERENCIA DE PROYECTOS', 'ADMINISTRACIÓN DE OPERACIONES'], shelf: '20' },
  { topics: ['MERCADEO', 'INGENIERÍA QUÍMICA', 'PROCESOS QUÍMICOS'], shelf: '21' },
  { topics: ['QUÍMICA INDUSTRIAL', 'TECNOLOGÍA DE ALIMENTOS', 'PETRÓLEO'], shelf: '21' },
  { topics: ['PLÁSTICOS', 'POLÍMEROS', 'METALURGÍA'], shelf: '22' },
  { topics: ['MANUFACTURA', 'CONSTRUCCIÓN Y ACABADOS', 'LIBROS DE GRAN FORMATO'], shelf: '22' }
];

window.LibraryData.ROS_NAVIGATION = window.NavigationUtilitiesData || null;

window.LibraryData.HELP_CONFIG = {
  provider: 'formsubmit',
  recipient: 'm.estupinanm@uniandes.edu.co',
  senderName: 'Nova',
  formsubmit: {
    endpointBase: 'https://formsubmit.co/ajax/',
    subject: 'Nova necesita ayuda',
    captcha: false,
    template: 'table'
  }
};

window.LibraryData.SUPABASE = {
  url: 'https://pzfbafvkaxpvmdnrvoee.supabase.co',
  key: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6ZmJhZnZrYXhwdm1kbnJ2b2VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3MjEyODYsImV4cCI6MjA5MTI5NzI4Nn0.gX4dX7bKD8p_V5y1TktKEU_LVGmMHmwQdJfWf5VAPjE'
};
})();
