(function () {
  'use strict';

  window.LibraryData = window.LibraryData || {};

window.LibraryData.MAP_IMAGE_ES = './assets/images/ESPANOL.png';
window.LibraryData.MAP_IMAGE_EN = './assets/images/INGLES.png';
window.LibraryData.ACTIVITIES_URL = './assets/data/activities.json';

window.LibraryData.STRINGS = {
  es: {
    'nav.back': 'Volver',
    'idle.hint': 'Toca la pantalla para comenzar',
    'help.button': 'Ayuda',
    'help.title': 'Necesitas ayuda?',
    'help.message': 'Un bibliotecario ha sido notificado y vendra a asistirte. Por favor espera aqui.',
    'help.dismiss': 'Cerrar',
    'help.location_unknown': 'No registrada',
    'menu.title': '¿Cómo puedo ayudarte?',
    'menu.navigation': '¿A dónde voy?',
    'menu.navigation.desc': 'Te guío paso a paso a tu destino',
    'menu.shelves': 'Buscar libro',
    'menu.shelves.desc': 'Busca por tema en las estanterías',
    'menu.books': 'Servicios de libros',
    'menu.books.desc': 'Préstamo y devolución',
    'menu.info': 'Información',
    'menu.info.desc': 'Horarios, noticias y preguntas frecuentes',
    'menu.events': 'Eventos',
    'menu.events.desc': 'Trivia y actividades',
    'menu.primary_service': 'Servicio principal',
    'menu.start': 'Comenzar',
    'menu.start_arrow': 'Comenzar ➔',

    'nav.you_are_here': 'Aquí estás',
    'nav.your_dest': 'Tu destino',
    'nav.screen_title': 'Selecciona un destino',
    'nav.cat.rooms': 'Salas de estudio',
    'nav.cat.services': 'Servicios',
    'nav.cat.access': 'Accesos',
    'nav.guide_me': 'Llevame',
    'nav.done': 'Listo',
    'nav.directions': 'Indicaciones',
    'nav.map_label': 'Mapa del piso',
    'nav.quick_hint': 'Elige un destino y te mostrare la ruta en el mapa',
    'dest.reception': 'Recepción',
    'dest.coordination': 'Coordinación',
    'dest.elevator': 'Ascensor',
    'dest.stairs_up': 'Escaleras subida',
    'dest.stairs_down': 'Escaleras bajada',
    'dest.stairs_emergency': 'Escaleras emergencia ',
    'dest.restroom_m': 'Baño hombres',
    'dest.restroom_f': 'Baño mujeres',
    'dest.restroom_accessible': 'Baño minusválidos',
    'dest.room_251': 'Sala 251',
    'dest.room_252c': 'Sala 252C',
    'dest.room_254': 'Sala 254',
    'dest.room_255': 'Sala 255',
    'dest.room_255a': 'Sala 255A',
    'dest.room_255b': 'Sala 255B',
    'dest.room_255c': 'Sala 255C',
    'dest.room_255d': 'Sala 255D',
    'dest.room_256': 'Sala 256',
    'dest.room_257': 'Sala 257',
    'dest.room_259a': 'Sala 259A',
    'dest.room_259g': 'Sala 259G',
    'dest.book_lift': 'Subidor de libros',
    'dest.material_maintenance_workshop': 'Taller mantenimiento material',
    'dest.sterilization_space': 'Espacio esterilización',
    'dest.map.restroom_accessible': 'Baño minusválidos',
    'dest.map.material_maintenance_workshop': 'Taller material',
    'dest.map.book_lift': 'Subidor de libros',
    'dest.col_engineering': 'Ingenieria',
    'dest.col_sciences': 'Ciencias',
    'dest.col_humanities': 'Humanidades',
    'dest.col_social': 'Ciencias sociales',
    'dest.col_arts': 'Artes',
    'dest.entry': 'Entrada',
    'dest.exit': 'Salida',
    'books.screen_title': 'Servicios de libros',
    'books.borrow': 'Prestamo',
    'books.borrow_desc': 'Quiero pedir un libro',
    'books.return': 'Devolucion',
    'books.return_desc': 'Quiero devolver un libro',
    'books.borrow_title': 'Prestamo de libros',
    'books.borrow_message': 'Para solicitar un prestamo, por favor dirigete a Recepcion donde un bibliotecario te asistira, o utiliza la estacion de autoservicio.',
    'books.return_title': 'Devolucion de libros',
    'books.return_message': 'Para devolver un libro, por favor dirigete a Recepcion o utiliza el buzon de devolucion disponible en el primer piso.',
    'books.go_reception': 'Llevame a Recepcion',
    'books.back_options': 'Volver a opciones',
    'books.hero_eyebrow': 'Servicios disponibles',
    'books.hero_title': 'Prestamo y devolucion sin perderte',
    'books.hero_copy': 'Selecciona lo que quieres hacer y te mostrare los pasos mas claros para continuar en la biblioteca.',
    'info.screen_title': 'Informacion',
    'info.hours': 'Horarios',
    'info.news': 'Noticias',
    'info.faq': 'Preguntas frecuentes',
    'info.today': 'Hoy',
    'info.news_title': 'Noticias Uniandes',
    'info.news_copy': 'Consulta las noticias mas recientes directamente desde el portal oficial de la Universidad.',
    'info.news_cta': 'Abrir noticias',
    'info.news_hint': 'Si el panel no carga, usa este acceso directo.',
    'info.hours_value': '7:00 AM - 9:00 PM',
    'info.day_mon': 'Lunes',
    'info.day_tue': 'Martes',
    'info.day_wed': 'Miercoles',
    'info.day_thu': 'Jueves',
    'info.day_fri': 'Viernes',
    'info.day_sat': 'Sabado',
    'info.day_sun': 'Domingo',
    'info.closed': 'Cerrado',
    'events.screen_title': 'Eventos',
    'events.trivia_title': 'Trivia de la Biblioteca',
    'events.trivia_desc': 'Pon a prueba tus conocimientos sobre la biblioteca y la universidad. 5 preguntas rapidas!',
    'events.start': 'Comenzar',
    'events.question': 'Pregunta',
    'events.of': 'de',
    'events.score': 'Puntos',
    'events.next': 'Siguiente',
    'events.result_title': 'Resultado final',
    'events.result_great': 'Excelente!',
    'events.result_good': 'Bien hecho!',
    'events.result_ok': 'Sigue intentando!',
    'events.play_again': 'Jugar de nuevo',
    'events.back_menu': 'Volver al menu',
    'events.select_activity': 'Elige una actividad',
    'events.available_now': 'Disponible ahora',
    'events.coming_soon': 'Proximamente',
    'events.badge_trivia': 'Trivia',
    'events.badge_game': 'Juego',
    'events.library_arcade': 'Zona de eventos',
    'shelves.screen_title': 'Buscar libro por tema',
    'shelves.panel_hint': 'Toca una estanteria para ver sus temas',
    'shelves.search_placeholder': 'Busca un tema...',
    'shelves.search_meta_default': 'Explora las estanterias o escribe un tema.',
    'shelves.search_results': 'resultados',
    'shelves.search_empty': 'No encontramos coincidencias. Intenta con otra palabra clave.',
    'shelves.select_hint': 'Selecciona una estanteria para ver su ubicacion',
    'shelves.shelf_label': 'Estanteria',
    'shelves.section_label': 'Seccion',
    'shelves.no_results': 'Sin resultados para tu busqueda',
    'shelves.topics_count': 'temas',
    'shelves.view_topics': 'Ver temas',
    'shelves.hide_topics': 'Ocultar temas',
    'shelves.tap_topic': 'Toca un tema para ver la ubicacion',
    'feedback.title': 'Como fue tu experiencia?',
    'feedback.bad': 'Mala',
    'feedback.ok': 'Regular',
    'feedback.great': 'Buena',
    'feedback.excelente': 'Excelente',
    'feedback.bueno': 'Bueno',
    'feedback.regular': 'Regular',
    'feedback.malo': 'Malo',
    'feedback.pesimo': 'Pesimo',
    'feedback.thanks': 'Gracias por tu opinion!',
    'feedback.caption': 'Tu opinion ayuda a que Nova atienda mejor',
    'feedback.comment_prompt': 'Quieres agregar algun comentario? (opcional)',
    'feedback.comment_placeholder': 'Escribe aqui tu comentario...',
    'feedback.send': 'Enviar'
  },
  en: {
    'nav.back': 'Back',
    'idle.hint': 'Touch the screen to start',
    'help.button': 'Help',
    'help.title': 'Need help?',
    'help.message': 'A librarian has been notified and will come to assist you. Please wait here.',
    'help.dismiss': 'Close',
    'help.location_unknown': 'Not recorded',
    'menu.title': 'How can I help you?',
    'menu.navigation': 'Where do I go?',
    'menu.navigation.desc': "I'll guide you step by step to your destination",
    'menu.shelves': 'Search for books',
    'menu.shelves.desc': 'Search by subject on the shelves',
    'menu.books': 'Book services',
    'menu.books.desc': 'Borrow and return',
    'menu.info': 'Information',
    'menu.info.desc': 'Opening hours, news, and FAQs',
    'menu.events': 'Events',
    'menu.events.desc': 'Trivia and activities',
    'menu.primary_service': 'Main service',
    'menu.start': 'Start',
    'menu.start_arrow': 'Start ➔',
    'nav.you_are_here': 'You are here',
    'nav.your_dest': 'Your destination',
    'nav.screen_title': 'Select a destination',
    'nav.cat.rooms': 'Study rooms',
    'nav.cat.services': 'Services',
    'nav.cat.access': 'Access points',
    'nav.guide_me': 'Guide me',
    'nav.done': 'Done',
    'nav.directions': 'Directions',
    'nav.map_label': 'Floor map',
    'nav.quick_hint': 'Choose a destination and I will show the route on the map',
    'dest.reception': 'Reception',
    'dest.coordination': 'Coordination',
    'dest.elevator': 'Elevator',
    'dest.stairs_up': 'Stairs up',
    'dest.stairs_down': 'Stairs down',
    'dest.stairs_emergency': 'Emergency stairs',
    'dest.restroom_m': "Men's restroom",
    'dest.restroom_f': "Women's restroom",
    'dest.restroom_accessible': 'Accessible restroom',
    'dest.room_251': 'Room 251',
    'dest.room_252c': 'Room 252C',
    'dest.room_254': 'Room 254',
    'dest.room_255': 'Room 255',
    'dest.room_255a': 'Room 255A',
    'dest.room_255b': 'Room 255B',
    'dest.room_255c': 'Room 255C',
    'dest.room_255d': 'Room 255D',
    'dest.room_256': 'Room 256',
    'dest.room_257': 'Room 257',
    'dest.room_259a': 'Room 259A',
    'dest.room_259g': 'Room 259G',
    'dest.book_lift': 'Book lift',
    'dest.material_maintenance_workshop': 'Material maintenance workshop',
    'dest.sterilization_space': 'Sterilization space',
    'dest.map.restroom_accessible': 'Accessible restroom',
    'dest.map.material_maintenance_workshop': 'Material workshop',
    'dest.map.book_lift': 'Book lift',
    'dest.col_engineering': 'Engineering',
    'dest.col_sciences': 'Sciences',
    'dest.col_humanities': 'Humanities',
    'dest.col_social': 'Social sciences',
    'dest.col_arts': 'Arts',
    'dest.entry': 'Entrance',
    'dest.exit': 'Exit',
    'books.screen_title': 'Book services',
    'books.borrow': 'Borrow',
    'books.borrow_desc': 'I want to borrow a book',
    'books.return': 'Return',
    'books.return_desc': 'I want to return a book',
    'books.borrow_title': 'Book borrowing',
    'books.borrow_message': 'To borrow a book, please go to Reception where a librarian will assist you, or use the self-checkout station.',
    'books.return_title': 'Book return',
    'books.return_message': 'To return a book, please go to Reception or use the return drop-box available on the first floor.',
    'books.go_reception': 'Take me to Reception',
    'books.back_options': 'Back to options',
    'books.hero_eyebrow': 'Available services',
    'books.hero_title': 'Borrowing and returns without the guesswork',
    'books.hero_copy': 'Choose what you need and I will show the clearest next step inside the library.',
    'info.screen_title': 'Information',
    'info.hours': 'Hours',
    'info.news': 'News',
    'info.faq': 'Frequently asked questions',
    'info.today': 'Today',
    'info.news_title': 'Uniandes news',
    'info.news_copy': 'Check the latest stories directly from the official Universidad de los Andes news portal.',
    'info.news_cta': 'Open news',
    'info.news_hint': 'If the panel does not load, use this direct access.',
    'info.hours_value': '7:00 AM - 9:00 PM',
    'info.day_mon': 'Monday',
    'info.day_tue': 'Tuesday',
    'info.day_wed': 'Wednesday',
    'info.day_thu': 'Thursday',
    'info.day_fri': 'Friday',
    'info.day_sat': 'Saturday',
    'info.day_sun': 'Sunday',
    'info.closed': 'Closed',
    'events.screen_title': 'Events',
    'events.trivia_title': 'Library Trivia',
    'events.trivia_desc': 'Test your knowledge about the library and the university. 5 quick questions!',
    'events.start': 'Start',
    'events.question': 'Question',
    'events.of': 'of',
    'events.score': 'Score',
    'events.next': 'Next',
    'events.result_title': 'Final result',
    'events.result_great': 'Excellent!',
    'events.result_good': 'Well done!',
    'events.result_ok': 'Keep trying!',
    'events.play_again': 'Play again',
    'events.back_menu': 'Back to menu',
    'events.select_activity': 'Choose an activity',
    'events.available_now': 'Available now',
    'events.coming_soon': 'Coming soon',
    'events.badge_trivia': 'Trivia',
    'events.badge_game': 'Game',
    'events.library_arcade': 'Events arcade',
    'shelves.screen_title': 'Find book by topic',
    'shelves.panel_hint': 'Tap a shelf to see its topics',
    'shelves.search_placeholder': 'Search a topic...',
    'shelves.search_meta_default': 'Browse the shelves or type a topic.',
    'shelves.search_results': 'results',
    'shelves.search_empty': 'No matches found. Try another keyword.',
    'shelves.select_hint': 'Select a shelf to see its location',
    'shelves.shelf_label': 'Shelf',
    'shelves.section_label': 'Section',
    'shelves.no_results': 'No results for your search',
    'shelves.topics_count': 'topics',
    'shelves.view_topics': 'View topics',
    'shelves.hide_topics': 'Hide topics',
    'shelves.tap_topic': 'Tap a topic to see its location',
    'feedback.title': 'How was your experience?',
    'feedback.bad': 'Bad',
    'feedback.ok': 'Okay',
    'feedback.great': 'Great',
    'feedback.excelente': 'Excellent',
    'feedback.bueno': 'Good',
    'feedback.regular': 'Okay',
    'feedback.malo': 'Bad',
    'feedback.pesimo': 'Very bad',
    'feedback.thanks': 'Thank you for your feedback!',
    'feedback.caption': 'Your feedback helps Nova assist better',
    'feedback.comment_prompt': 'Would you like to add a comment? (optional)',
    'feedback.comment_placeholder': 'Write your comment here...',
    'feedback.send': 'Send'
  }
};

window.LibraryData.SCREEN_TITLES = {
  menu: 'menu.title',
  navigation: 'nav.screen_title',
  'navigation-guide': 'nav.directions',
  shelves: 'shelves.screen_title',
  books: 'books.screen_title',
  info: 'info.screen_title',
  events: 'events.screen_title',
  feedback: 'feedback.title'
};

window.LibraryData.TOPBAR_SCREENS = ['menu', 'navigation', 'navigation-guide', 'shelves', 'books', 'info', 'events', 'feedback'];

window.LibraryData.MENU_CATEGORIES = {
  navigation: '¿A donde voy?',
  shelves: 'Buscar libro',
  books: 'Servicios de libro',
  info: 'Informacion',
  events: 'Eventos'
};

window.LibraryData.NAV_DEST_CATEGORIES = {
  room_251: 'rooms',
  room_252c: 'rooms',
  room_254: 'rooms',
  room_255: 'rooms',
  room_255a: 'rooms',
  room_255b: 'rooms',
  room_255c: 'rooms',
  room_255d: 'rooms',
  room_256: 'rooms',
  room_257: 'rooms',
  room_259a: 'rooms',
  room_259g: 'rooms',
  reception: 'services',
  coordination: 'services',
  restroom_m: 'services',
  restroom_f: 'services',
  restroom_accessible: 'services',
  material_maintenance_workshop: 'services',
  sterilization_space: 'services',
  book_lift: 'services',
  entry: 'access',
  exit: 'access',
  elevator: 'access',
  stairs_up: 'access',
  stairs_down: 'access',
  stairs_emergency: 'access'
};

window.LibraryData.DEST_CATEGORY_LABELS = {
  rooms: 'Salas de estudio',
  services: 'Servicios',
  access: 'Accesos'
};

window.LibraryData.NAV_CATEGORIES = [
  {
    id: 'rooms',
    titleKey: 'nav.cat.rooms',
    items: [
      { id: 'room_251', nameKey: 'dest.room_251' },
      { id: 'room_252c', nameKey: 'dest.room_252c' },
      { id: 'room_254', nameKey: 'dest.room_254' },
      { id: 'room_255', nameKey: 'dest.room_255' },
      { id: 'room_255a', nameKey: 'dest.room_255a' },
      { id: 'room_255b', nameKey: 'dest.room_255b' },
      { id: 'room_255c', nameKey: 'dest.room_255c' },
      { id: 'room_255d', nameKey: 'dest.room_255d' },
      { id: 'room_256', nameKey: 'dest.room_256' },
      { id: 'room_257', nameKey: 'dest.room_257' },
      { id: 'room_259a', nameKey: 'dest.room_259a' },
      { id: 'room_259g', nameKey: 'dest.room_259g' }
    ]
  },
  {
    id: 'services',
    titleKey: 'nav.cat.services',
    items: [
      { id: 'reception', nameKey: 'dest.reception' },
      { id: 'coordination', nameKey: 'dest.coordination' },
      { id: 'restroom_m', nameKey: 'dest.restroom_m' },
      { id: 'restroom_f', nameKey: 'dest.restroom_f' },
      { id: 'restroom_accessible', nameKey: 'dest.restroom_accessible' },
      { id: 'material_maintenance_workshop', nameKey: 'dest.material_maintenance_workshop' },
      { id: 'sterilization_space', nameKey: 'dest.sterilization_space' },
      { id: 'book_lift', nameKey: 'dest.book_lift' }
    ]
  },
  {
    id: 'access',
    titleKey: 'nav.cat.access',
    items: [
      { id: 'entry', nameKey: 'dest.entry' },
      { id: 'exit', nameKey: 'dest.exit' },
      { id: 'elevator', nameKey: 'dest.elevator' },
      { id: 'stairs_up', nameKey: 'dest.stairs_up' },
      { id: 'stairs_down', nameKey: 'dest.stairs_down' },
      { id: 'stairs_emergency', nameKey: 'dest.stairs_emergency' }
    ]
  }
];

window.LibraryData.MAP_COORDS = {
  you_are_here: { x: 44.5, y: 43 },
  reception: { x: 43.76, y: 22 },
  coordination: { x: 94.6, y: 10 },
  elevator: { x: 59.4, y: 22 },
  stairs_up: [
    { x: 41.7, y: 44 },
    { x: 60.3, y: 44 }
  ],
  stairs_down: [
    { x: 41.7, y: 80.5 },
    { x: 60.3, y: 80.5 }
  ],
  stairs_emergency: [
    { x: 29.9, y: 32.5 },
    { x: 70, y: 32.5 }
  ],
  entry: { x: 51.2, y: 21 },
  exit: { x: 62.92, y: 22 },
  book_lift: { x: 39.65, y: 19 },
  material_maintenance_workshop: { x: 3.5, y: 37 },
  sterilization_space: { x: 6.5, y: 76.2 },
  restroom_m: { x: 76.53, y: 32.5 },
  restroom_f: { x: 21.72, y: 32.5 },
  restroom_accessible: { x: 17.76, y: 32.5 },
  room_251: { x: 22.14, y: 45.8 },
  room_252c: { x: 6.5, y: 90 },
  room_254: { x: 96.3, y: 40.1 },
  room_255: { x: 96.3, y: 32.6 },
  room_255a: { x: 56.38, y: 71 },
  room_255b: { x: 52.72, y: 71 },
  room_255c: { x: 49.11, y: 71 },
  room_255d: { x: 45.51, y: 71 },
  room_256: { x: 96.3, y: 25.1 },
  room_257: { x: 96.3, y: 17.6 },
  room_259a: { x: 79.65, y: 32.5 },
  room_259g: { x: 79.22, y: 45.8 },
  shelf_01: { x: 9, y: 35 },
  shelf_02: { x: 15, y: 35 },
  shelf_03: { x: 21, y: 35 },
  shelf_04: { x: 27, y: 35 },
  shelf_05: { x: 33, y: 35 },
  shelf_06: { x: 9, y: 58 },
  shelf_07: { x: 15, y: 58 },
  shelf_08: { x: 21, y: 58 },
  shelf_09: { x: 27, y: 58 },
  shelf_10: { x: 33, y: 58 },
  shelf_11: { x: 39, y: 45 },
  shelf_12: { x: 54, y: 30 },
  shelf_13: { x: 61, y: 30 },
  shelf_14: { x: 67, y: 30 },
  shelf_15: { x: 73, y: 30 },
  shelf_16: { x: 79, y: 30 },
  shelf_17: { x: 54, y: 55 },
  shelf_18: { x: 61, y: 55 },
  shelf_19: { x: 67, y: 55 },
  shelf_20: { x: 73, y: 55 },
  shelf_21: { x: 79, y: 55 },
  shelf_22: { x: 85, y: 55 }
};

window.LibraryData.HOURS = {
  schedule: [
    { dayKey: 'info.day_mon', time: '7:00 AM - 9:00 PM' },
    { dayKey: 'info.day_tue', time: '7:00 AM - 9:00 PM' },
    { dayKey: 'info.day_wed', time: '7:00 AM - 9:00 PM' },
    { dayKey: 'info.day_thu', time: '7:00 AM - 9:00 PM' },
    { dayKey: 'info.day_fri', time: '7:00 AM - 9:00 PM' },
    { dayKey: 'info.day_sat', time: '8:00 AM - 4:00 PM' },
    { dayKey: 'info.day_sun', closedKey: 'info.closed' }
  ]
};

window.LibraryData.FAQS = [
  {
    q: { es: 'Como puedo prestar un libro?', en: 'How can I borrow a book?' },
    a: { es: 'Dirigete a Recepcion con tu carnet universitario. El personal te asistira con el proceso de prestamo. Tambien puedes usar la estacion de autoservicio.', en: 'Go to Reception with your university ID. Staff will assist you with the borrowing process. You can also use the self-checkout station.' }
  },
  {
    q: { es: 'Cuantos libros puedo tener prestados?', en: 'How many books can I have on loan?' },
    a: { es: 'Los estudiantes de pregrado pueden tener hasta 5 libros prestados simultaneamente. Estudiantes de posgrado pueden tener hasta 8.', en: 'Undergraduate students can have up to 5 books on loan simultaneously. Graduate students can have up to 8.' }
  },
  {
    q: { es: 'Donde estan los banos?', en: 'Where are the restrooms?' },
    a: { es: 'Los banos estan ubicados en el costado derecho de la biblioteca. Puedes usar la opcion "Adonde voy?" para que te guie.', en: 'The restrooms are located on the right side of the library. You can use the "Where do I go?" option for directions.' }
  },
  {
    q: { es: 'Puedo reservar una sala de estudio?', en: 'Can I reserve a study room?' },
    a: { es: 'Si, las salas de estudio se pueden reservar a traves del sistema IRUS o directamente en Recepcion.', en: 'Yes, study rooms can be reserved through the IRUS system or directly at Reception.' }
  },
  {
    q: { es: 'Hay impresoras disponibles?', en: 'Are printers available?' },
    a: { es: 'Si, hay impresoras disponibles para los estudiantes. Consulta en Recepcion sobre el servicio de impresion.', en: 'Yes, printers are available for students. Ask at Reception about the printing service.' }
  },
  {
    q: { es: 'Que hago si pierdo un libro prestado?', en: 'What if I lose a borrowed book?' },
    a: { es: 'Dirigete a Recepcion lo antes posible para reportar la perdida. El personal te indicara el procedimiento a seguir.', en: 'Go to Reception as soon as possible to report the loss. Staff will guide you through the procedure.' }
  }
];

window.LibraryData.TAB_SERVICE_MAP = {
  hours: 'Informacion',
  news: 'Noticias',
  faq: 'Preguntas frecuentes'
};

window.LibraryData.RATING_MAP = {
  excelente: 'Excelente',
  bueno: 'Bueno',
  regular: 'Regular',
  malo: 'Malo',
  pesimo: 'Pesimo'
};

window.LibraryData.SHELF_NUMBERS = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22'];

window.LibraryData.SHELF_TOPICS = [
  { topics: ['SIMULACION', 'ARQUITECTURA DE SOFTWARE'], shelf: '01', coordKey: 'shelf_01' },
  { topics: ['REDES Y CONECTIVIDAD', 'INTELIGENCIA ARTIFICIAL'], shelf: '01', coordKey: 'shelf_01' },
  { topics: ['SISTEMAS OPERATIVOS', 'BASES DE DATOS'], shelf: '02', coordKey: 'shelf_02' },
  { topics: ['SEGURIDAD INFORMATICA', 'INTELIGENCIA ARTIFICIAL', 'DISENO MULTIMEDIA'], shelf: '02', coordKey: 'shelf_02' },
  { topics: ['LENGUAJES DE PROGRAMACION', 'SISTEMAS OPERATIVOS'], shelf: '02', coordKey: 'shelf_02' },
  { topics: ['METODOLOGIA CIENTIFICA', 'FILOSOFIA DE LA CIENCIA'], shelf: '02', coordKey: 'shelf_02' },
  { topics: ['MATEMATICAS - ENSENANZA', 'MATEMATICAS - FUNDAMENTOS'], shelf: '03', coordKey: 'shelf_03' },
  { topics: ['MATEMATICAS - HISTORIA', 'LOGICA MATEMATICA'], shelf: '03', coordKey: 'shelf_03' },
  { topics: ['CIENCIA Y TECNOLOGIA - HISTORIA', 'MATEMATICAS'], shelf: '03', coordKey: 'shelf_03' },
  { topics: ['ALGEBRA', 'ALGEBRA LINEAL'], shelf: '03', coordKey: 'shelf_03' },
  { topics: ['TOPOLOGIA', 'CALCULO'], shelf: '04', coordKey: 'shelf_04' },
  { topics: ['CALCULO', 'PRE-CALCULO'], shelf: '04', coordKey: 'shelf_04' },
  { topics: ['ALGEBRA LINEAL', 'TEORIA DE LOS NUMEROS', 'TOPOLOGIA'], shelf: '04', coordKey: 'shelf_04' },
  { topics: ['CALCULO', 'ECUACIONES DIFERENCIALES'], shelf: '04', coordKey: 'shelf_04' },
  { topics: ['GEOMETRIA', 'PROBABILIDAD'], shelf: '05', coordKey: 'shelf_05' },
  { topics: ['PROBABILIDAD', 'TEORIA DEL JUEGO'], shelf: '05', coordKey: 'shelf_05' },
  { topics: ['CALCULO VECTORIAL', 'ANALISIS DE GEOMETRIA'], shelf: '05', coordKey: 'shelf_05' },
  { topics: ['TEORIA DEL JUEGO', 'ANALISIS NUMERICO', 'PROBABILIDAD'], shelf: '05', coordKey: 'shelf_05' },
  { topics: ['ESTADISTICA', 'ANALISIS MULTIVARIABLE'], shelf: '06', coordKey: 'shelf_06' },
  { topics: ['OPTIMIZACION', 'ASTRONOMIA'], shelf: '07', coordKey: 'shelf_07' },
  { topics: ['FISICA'], shelf: '08', coordKey: 'shelf_08' },
  { topics: ['FISICA - BIOGRAFIAS', 'RELATIVIDAD', 'TEORIA CUANTICA'], shelf: '08', coordKey: 'shelf_08' },
  { topics: ['COSMOLOGIA', 'TOPOGRAFIA', 'FISICA - FUNDAMENTOS'], shelf: '08', coordKey: 'shelf_08' },
  { topics: ['TEORIA CUANTICA', 'ELECTROMAGNETISMO'], shelf: '08', coordKey: 'shelf_08' },
  { topics: ['MECANICA ESTADISTICA', 'FISICA TERMODINAMICA', 'ELECTROMAGNETISMO'], shelf: '09', coordKey: 'shelf_09' },
  { topics: ['ELECTRODINAMICA', 'FISICA NUCLEAR'], shelf: '09', coordKey: 'shelf_09' },
  { topics: ['MECANICA DE FLUIDOS', 'OPTICA'], shelf: '09', coordKey: 'shelf_09' },
  { topics: ['MODELOS NUCLEARES', 'QUIMICA GENERAL'], shelf: '09', coordKey: 'shelf_09' },
  { topics: ['ANALISIS QUIMICO', 'QUIMICA INORGANICA'], shelf: '10', coordKey: 'shelf_10' },
  { topics: ['QUIMICA ORGANICA'], shelf: '10', coordKey: 'shelf_10' },
  { topics: ['FISICOQUIMICA', 'QUIMICA TERMODINAMICA'], shelf: '10', coordKey: 'shelf_10' },
  { topics: ['MACROMOLECULAS', 'MINERALES', 'GEOLOGIA'], shelf: '10', coordKey: 'shelf_10' },
  { topics: ['ANTROPOLOGIA BIOLOGICA', 'BIOLOGIA'], shelf: '11', coordKey: 'shelf_11' },
  { topics: ['BIOESTADISTICA'], shelf: '11', coordKey: 'shelf_11' },
  { topics: ['METEOROLOGIA', 'GEOQUIMICA'], shelf: '11', coordKey: 'shelf_11' },
  { topics: ['BIOQUIMICA', 'ECOLOGIA'], shelf: '11', coordKey: 'shelf_11' },
  { topics: ['MICROBIOLOGIA', 'BOTANICA'], shelf: '12', coordKey: 'shelf_12' },
  { topics: ['FITOPATOLOGIA'], shelf: '12', coordKey: 'shelf_12' },
  { topics: ['BIOLOGIA MOLECULAR', 'GENETICA', 'MICROBIOLOGIA'], shelf: '12', coordKey: 'shelf_12' },
  { topics: ['MICOLOGIA', 'ZOOLOGIA', 'INVERTEBRADOS'], shelf: '12', coordKey: 'shelf_12' },
  { topics: ['DIBUJO EN INGENIERIA', 'HISTORIA DE LA TECNOLOGIA', 'INGENIERIA BIOMEDICA'], shelf: '13', coordKey: 'shelf_13' },
  { topics: ['MEDICINA SOCIAL', 'ANATOMIA', 'HISTOLOGIA'], shelf: '13', coordKey: 'shelf_13' },
  { topics: ['INSECTOS', 'MAMIFEROS', 'AVES'], shelf: '13', coordKey: 'shelf_13' },
  { topics: ['FISIOLOGIA MEDICA', 'NEUROCIENCIA', 'MEDICINA FORENSE'], shelf: '13', coordKey: 'shelf_13' },
  { topics: ['PATOLOGIA', 'INMUNOLOGIA', 'HEMATOLOGIA'], shelf: '14', coordKey: 'shelf_14' },
  { topics: ['NEUROLOGIA', 'PSICOLOGIA CLINICA'], shelf: '14', coordKey: 'shelf_14' },
  { topics: ['FARMACOLOGIA', 'SALUD PUBLICA', 'MICROBIOLOGIA MEDICA'], shelf: '14', coordKey: 'shelf_14' },
  { topics: ['PSIQUIATRIA', 'ENFERMEDADES INFECCIOSAS', 'PEDIATRIA'], shelf: '14', coordKey: 'shelf_14' },
  { topics: ['MATERIALES', 'MECANICA APLICADA'], shelf: '15', coordKey: 'shelf_15' },
  { topics: ['MECANICA DE MATERIALES', 'COMPOSICION DE MATERIALES'], shelf: '15', coordKey: 'shelf_15' },
  { topics: ['INGENIERIA', 'DISENO DE INGENIERIA', 'INGENIERIA MECANICA'], shelf: '15', coordKey: 'shelf_15' },
  { topics: ['INGENIERIA DE POLIMEROS', 'NANOTECNOLOGIA', 'INGENIERIA ELECTRICA'], shelf: '15', coordKey: 'shelf_15' },
  { topics: ['TELECOMUNICACIONES', 'MICROELECTRONICA'], shelf: '16', coordKey: 'shelf_16' },
  { topics: ['ELECTRONICA', 'COMUNICACION DIGITAL'], shelf: '16', coordKey: 'shelf_16' },
  { topics: ['CIRCUITOS ELECTRICOS', 'PROCESAMIENTO DE SENALES'], shelf: '16', coordKey: 'shelf_16' },
  { topics: ['DISENO DIGITAL', 'TERMODINAMICA'], shelf: '16', coordKey: 'shelf_16' },
  { topics: ['INGENIERIA CIVIL', 'MECANICA DE SUELOS'], shelf: '17', coordKey: 'shelf_17' },
  { topics: ['INGENIERIA DE CARRETERAS', 'DISENO DE ESTRUCTURAS'], shelf: '17', coordKey: 'shelf_17' },
  { topics: ['INGENIERIA MECANICA', 'INGENIERIA DE PETROLEOS', 'INGENIERIA HIDRAULICA'], shelf: '17', coordKey: 'shelf_17' },
  { topics: ['INGENIERIA HIDRAULICA', 'INGENIERIA AMBIENTAL'], shelf: '17', coordKey: 'shelf_17' },
  { topics: ['INGENIERIA DEL AGUA', 'GESTION DE RESIDUOS'], shelf: '18', coordKey: 'shelf_18' },
  { topics: ['INGENIERIA AMBIENTAL', 'INGENIERIA AUTOMOTRIZ', 'SISTEMAS DE CONTROL Y ROBOTICA'], shelf: '19', coordKey: 'shelf_19' },
  { topics: ['AGRICULTURA', 'ZOOTECNIA', 'GASTRONOMIA'], shelf: '19', coordKey: 'shelf_19' },
  { topics: ['GASTRONOMIA', 'CONTABILIDAD', 'ADMINISTRACION'], shelf: '20', coordKey: 'shelf_20' },
  { topics: ['TOMA DE DECISIONES', 'GERENCIA DE PROYECTOS', 'ADMINISTRACION DE OPERACIONES'], shelf: '20', coordKey: 'shelf_20' },
  { topics: ['MERCADEO', 'INGENIERIA QUIMICA', 'PROCESOS QUIMICOS'], shelf: '21', coordKey: 'shelf_21' },
  { topics: ['QUIMICA INDUSTRIAL', 'TECNOLOGIA DE ALIMENTOS', 'PETROLEO'], shelf: '21', coordKey: 'shelf_21' },
  { topics: ['PLASTICOS', 'POLIMEROS', 'METALURGIA'], shelf: '22', coordKey: 'shelf_22' },
  { topics: ['MANUFACTURA', 'CONSTRUCCION Y ACABADOS', 'LIBROS DE GRAN FORMATO'], shelf: '22', coordKey: 'shelf_22' }
];

window.LibraryData.ROS_NAVIGATION = window.NavigationUtilitiesData || null;

window.LibraryData.HELP_CONFIG = {
  provider: 'formsubmit',
  recipient: 'm.estupinanm@uniandes.edu.co',
  senderName: 'Nova',
  formsubmit: {
    endpointBase: 'https://formsubmit.co/ajax/',
    subject: 'Nova necesita ayuda',
    captcha: false,
    template: 'table'
  }
};

window.LibraryData.SUPABASE = {
  url: 'https://pzfbafvkaxpvmdnrvoee.supabase.co',
  key: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6ZmJhZnZrYXhwdm1kbnJ2b2VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3MjEyODYsImV4cCI6MjA5MTI5NzI4Nn0.gX4dX7bKD8p_V5y1TktKEU_LVGmMHmwQdJfWf5VAPjE'
};
})();
